import { Dimensions } from 'react-native';

const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;

const DEVIATION_FACTOR_HEIGHT = 15;

const FIRSTCIRCLE_PROCENT = 0.3672;
const SECONDCIRCLE_PROCENT = 0.436;
const THIRDCIRCLE_PROCENT_WIDTH_PROCENT = 1.06;
const THIRDCIRCLE_PROCENT_HEIGHT_PROCENT = 0.83;

const FIRST_CIRCLE_HEIGHT =
  windowHeight * FIRSTCIRCLE_PROCENT + DEVIATION_FACTOR_HEIGHT;
const SECONDCIRCLE_HEIGHT =
  windowHeight * SECONDCIRCLE_PROCENT + DEVIATION_FACTOR_HEIGHT;
const FIRST_CIRCLE_WIDTH = windowHeight * FIRSTCIRCLE_PROCENT;
const SECONDCIRCLE_WIDTH = windowHeight * SECONDCIRCLE_PROCENT;
const THIRDCIRCLE_PROCENT_WIDTH =
  windowWidth * THIRDCIRCLE_PROCENT_WIDTH_PROCENT;
const THIRDCIRCLE_PROCENT_HEIGHT =
  windowHeight * THIRDCIRCLE_PROCENT_HEIGHT_PROCENT + DEVIATION_FACTOR_HEIGHT;

const CIRCLES_DIMENSIONS = {
  firstCircleHeight: FIRST_CIRCLE_HEIGHT,
  secondCircleHeight: SECONDCIRCLE_HEIGHT,
  firstCircleWidth: FIRST_CIRCLE_WIDTH,
  secondCircleWidth: SECONDCIRCLE_WIDTH,
  thirdCircleWidth: THIRDCIRCLE_PROCENT_WIDTH,
  thirdCircleHeight: THIRDCIRCLE_PROCENT_HEIGHT,
};

export default CIRCLES_DIMENSIONS;
